### PR TITLE
Add instructions for exiting Medley

### PR DESCRIPTION
**Pull request by pamoroso**
To address [issue #1332](https://github.com/Interlisp/medley/issues/1332) I added instructions for exiting Medley.

### CODE REVIEW

**Comment by masinter** [comment]
@rmkaplan note it uses il and not li for the default home dir (vs PSEUDOHOSTS).
@fghalasz note that this is patching the current install-and-run instructions if you're working on new ones.

**Review by stumbo — APPROVED** [review]

**Comment by pamoroso** [comment]
Is @fghalasz working on similar changes to these pages?

**Comment by pamoroso** [comment]
How can we proceed? Should I withdraw or modify this PR?

**Comment by masinter** [comment]
these changes don't seem to conflict with what I believe @fghalasz is doing to the install instructions.

for myself, I just close the window or type a control-C to the shell terminal where I started medley.

**Pull request merged**
