### PR TITLE
Gather the Zotero collections information during scripts/update_bibliography.sh.

### PR DESCRIPTION
**Pull request by MattHeffron**
Currently it is just put into `scripts/collections.json`, as nothing is using it yet.

See [Issue #1534](/Interlisp/medley/issues/1534)

### CODE REVIEW

**Review by stumbo — COMMENTED** [review]
We may want to add `collections.json` to the `.gitignore` file.  And, some point when we want to use the data, that will ensure the version we're using accurately reflects the current hierarchy.

**Comment by MattHeffron** [comment]
Until we decide _how_ to use it I'd just leave it as is.
We may want that file to be re-structured.
And it probably would be located in the data folder with the `bibliography.json` file.

**Comment by stumbo** [comment]
Agreed - I converted it to a draft PR just to make sure it doesn't get accidentally merged.

**Comment by MattHeffron** [comment]
@skaisler1 : Now that we know that we _can_ identify each bibliography entry by its Zotero collection, how do you think that we should use that for filtering? (In concept, which collections?) Allowing to select from the full set (or hierarchy) of collections seems overkill ... or not?

@phantomics : regarding this idea of being able to filter the display of bibliography items, it seems that's the kind of _magic_ that can be done with CSS, and you are the expert in that area. Do you have thoughts on how we can use the Zotero collection IDs (8 character alphanumeric) to show/hide (enable/disable display) of entries? And what about the **Year** headings, should they hide if **all** of their entries are hidden?

@masinter You should approve, _or not_, and prioritize Andrew on the above, with respect to other tasks.

**Comment by MattHeffron** [comment]
**All:** Please see the discussion on a new organization of the bibliography in Issue 1534: [Getting Zotero collection names for "smarter" bibliography](/Interlisp/medley/issues/1534)

**Comment by MattHeffron** [comment]
The changes here are included in PR #242, but this branch is not a parent of that branch.
I'm closing this as superseded.

**Pull request closed without merging**
