### PR TITLE
Fix history section

### PR DESCRIPTION
**Pull request by stumbo**
Cleans up the markdown, updates broken links, some minor editing.

### CODE REVIEW

**Review by masinter — COMMENTED** [review]
Should the photos move from Google Drive to the web site?
I think we might be able to annotate many of them with names and links to publications about what they would demo at AAAI in 1982, for example.

**Comment by stumbo** [comment]
> Should the photos move from Google Drive to the web site? I think we might be able to annotate many of them with names and links to publications about what they would demo at AAAI in 1982, for example.

I think it would be good to add them to the web site.  And, yes, we should identify the individuals in the pictures.  I could make some guesses, but it would be helpful for someone that was there or at least knows the 1980 version of everyone to identify the participants.  

I'll go ahead and get them pulled in.  We can then spend time labeling the pictures appropriately.

**Comment by masinter** [comment]
there are comments for the pictures when viewed from google photos.

**Comment by stumbo** [comment]
> there are comments for the pictures when viewed from google photos.

OK, I'll ask the dumb question.  How does one get Google Photo to open the pictures?   I see a collection of jpg files and a gdoc named 'Who's in these pictures' that I can't open. If I open one of the jpg files  I get the content in a viewer that doesn't show the metadata.

**Comment by masinter** [comment]
photo album https://photos.app.goo.gl/826EbhnkQSl8rePE3 click on "Activity" (cartoon speech bubble) in upper-right menu.   It looks like Google Photos lost the association of photos to captions, though.

I can figure out by matching, let me know how to communicate to you
image

**Pull request merged**
