### PR TITLE
rewrite history paragraphs

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Comment by stumbo** [comment]
Superseded by #194?

**Comment by masinter** [comment]
i'm not sure what I did, but this looks like it's a mistake.

**Comment by masinter** [comment]
This was closed but some of the edits might still be useful? would like opinions @stumbo @phantomics @pamoroso plese.

**Comment by masinter** [comment]
I figured out what happened: I went back to main to do the project _index.md where I wrote a long section on other PARC environments and wound up moving into history.

anyway PR #194 is the one to review.
e

**Comment by pamoroso** [comment]
In general I don't mind some overlap across sections of the site as the history of the various features and goals of Medley overlaps with the developments in a number of fields and industry trends.

More specifically, in #191 I'd keep the deleted sections as they add valuable historical context. As for #194 it looks good to me.

**Pull request closed without merging**
