### PR TITLE
Added description of pixel doubling on macOS.

### PR DESCRIPTION
**Pull request by hjellinek**
Medley is too tiny on my very large display.  Here's how to deal with that on a Mac.

### CODE REVIEW

**Review by masinter — CHANGES_REQUESTED** [review]
(1) We organized the web site so that
https://interlisp.org/software/install-and-run/macos/

contains complete instructions (or pointers to complete) for now to install and run on MacOS.

So doing this on a machine with a "large display" should be covered.

(3) I think we might need 3 FAQ's not 1 -- to cover
FAQ History (questions and answers about history of Interlisp and bibliography etc)
FAQ Software (about installing, running, using Medley today)
FAQ Project (about who we are and what wwe're doing).

A FAQ is where you put leftover answers to questions that don't fit into the documentation orientation.

**Comment by hjellinek** [comment]
That page (https://interlisp.org/software/install-and-run/macos/) is a well-written and complete description of running Medley under X on macOS.  The SDL implementation that enables pixel-doubling is not as mature as the X implementation.  I'd rather document the technique _somewhere_ so people can find it, even if we don't yet have the perfect location.  Put another way, I don't want to commit **Error 33**.

@masinter originally suggested adding it to the FAQ, which is what this PR does.

**Comment by hjellinek** [comment]
@masinter, you mentioned in our Weds meeting that you would approve this PR.  I'll merge it when you do.

**Comment by masinter** [comment]
My internet has been out several days and my neighbors have similar problems….So far att seems not ready to admit it’s a neighborhood problemWill approve--LarryMasinter.netOn Aug 25, 2024, at 2:08 PM, Herb Jellinek ***@***.***> wrote:﻿
@masinter, you mentioned in our Weds meeting that you would approve this PR.  I'll merge it when you do.

**Review by masinter — APPROVED** [review]

**Pull request merged**
