### PR TITLE
Adding reading lists of documentation resources

### PR DESCRIPTION
**Pull request by pamoroso**
As discussed in [issue 1131](https://github.com/Interlisp/medley/issues/1131) the new section *Getting started* in this PR contains two reading lists of documentation resources, one of introductory and the other of advanced material.

### CODE REVIEW

**Review by masinter — APPROVED** [review]
LGTM

**Comment by stumbo** [comment]
Try replacing `(Using)` with `(/software/Using.html)` this will match what we explicitly said the page address should be:

```
---
title: The Basics of Interlisp  
url: /software/Using.html  
type: docs  
weight: 2
---
```

That will get it referencing the right location.  I'm not sure why we put the url: in The Basics of Interlisp page, so I don't want to remove it.

**Comment by pamoroso** [comment]
I'll submit a separate fix for the link The Basics of Interlisp.

What about the broken links in section Exported Medley Documentation? They use HTML instead of Markdown syntax but the file names are likely missing the path. Where are those files stored?

PS Not sure whether this is the right place to comment on this or [here](https://github.com/Interlisp/medley/issues/1131)

**Comment by stumbo** [comment]
I'm not sure the best place -- but, my preference is to document PR issues as close to the PR as possible.  The format you want to use to address files in the documentation section is:

```
- [All Medley PDFS](https://interlisp.org/documentation/All-Medley-PDFs.pdf)
```

**Comment by pamoroso** [comment]
I submitted PR #195

**Pull request merged**
