### PR TITLE
Update docsy version to 0.10.0

### PR DESCRIPTION
**Pull request by stumbo**
Update Docsy version, cleaned up home page due to block handling changes.  Replaced twitter icon with X.

- Docsy Version bumped to 0.10.0
- Github action updates
  - peaceiris hugo action version  update -> v3
  - peaceiris gh-pages action version update -> v4
  - github cache action version update -> v4
  - github setup-node action version update -> v4
- Replaced deprecated `getJSON` call with `resources.Get`
  - Moved `data` directory location to `static/data`  so it would be treated as a resource location
  - Updated `update_bibliography.sh` script to build in new location
  - Update `bibTable` shortcut to use `resources.Get` method
  - Miscellaneous updates to fix minor style changes, primarily adding in values that are no longer defaulted
- Updates to `hugo.toml`
  - Removed deprecated type `taxonomyTerm` 
  - Removed deprecated `description` section in `[languages.en]`
  - `footer_about_disable` replaced by `footer_about_enable`
  - Twitter logo replaced with X logo

### CODE REVIEW

**Review by pamoroso — APPROVED** [review]
I'm actually unable to test this but it looks good to me.

**Comment by masinter** [comment]
just a caution -- should make sure there were no customizations of style or 404 page that might be affected ... it would be good to test this because they change how things work when they introduce a new version.

**Comment by stumbo** [comment]
My testing hasn't shown any impacts beyond what I needed to modify to get the landing page working correctly.  But, I also want to hear from @phantomics before merging.  I have a vague recollection of Andrew having some concerns about Docsy updates that effected his efforts to get the carousel working.

**Comment by stumbo** [comment]
Updated PR description with a more detailed list of the changes.  Tested both locally and deploying to a staging environment -- currently running at [Staging](https://stumbo.github.io/InterlispDraft.github.io/)

**Pull request merged**
