### PR TITLE
Prototype for new homepage.

### PR DESCRIPTION
**Pull request by stumbo**
This is a first take on how to convert Kathryn's homepage idea into something real.  The background image as it currently is, probably isn't the ending point.  There are also artifacts at the top that I need to delete.

I took the first three 'links' from Kathryn's layout and converted them  into blocks - they eventually need to have titles that are links to our documentation hierarchy.   And, the text within each block needs to be rewritten.  I put in the first few sentences that came to me as placeholders.

If this is closer to where we want to end up I'll continue refining it.  If not, I'll cut my losses and try something else.

Here's the current look:
image

### CODE REVIEW

**Comment by stumbo** [comment]
Second commit, adds a little more clean up.  The initial proposal is fully encompassed.  The links to sections of the documentation are captured:
image

Comments?  Is this headed in the right direction or going off the rails?

**Review by masinter — CHANGES_REQUESTED** [review]
I liked having 3 toplevel categories, not six:
- History: significance, apps, evolution 
- This project: who, what, participate, donate
- Try it

everything fits
discuss on zoom?

**Comment by stumbo** [comment]
Current background image:
image

I like the gradient idea, it needs to be a little less harsh on the edges.

**Comment by stumbo** [comment]
With my latest updates, the home page looks like this:
image

I want to add a chevron to jump to the next section - this picture was taken on my vertical display which allows me to capture the whole image, but on my regular horizontal displays you see the first two sections and the three blocks with links are off the bottom of the screen.

I like the general layout, the top image with the blue gradient is nice, but there's too much blue on the page now.  I'm going to switch the color to a gray and see it that looks better.  Other ideas on colors or background images are welcome.

The bottom section with the three boxes needs some work to align the buttons.  Once we have agreement on the text in each box, I'll focus attention on that.

The icons come form Font Awesome, I'm currently using ones that came with the code blocks, we can choose different ones that better convey the meaning of each section.  If you'd like to suggest changes here's a link to Font Awesome's icon collection:  https://fontawesome.com/v5/search

**Comment by stumbo** [comment]
Latest update, with grey landing page and white chevron down arrow:
image

Pressing the down arrow moves the *Home of the Medley Interlisp Project* to the top of the screen:
image

**Comment by KathrynLA** [comment]
This looks good. There are some typos. Please correct the text in above the links:
The Medley Interlisp Project
Be a part of preserving a seminal piece of software showcasing an early Human-Computer interaction platform.

Try Medley Interlisp
Follow instructions for running Medley Interlisp on a variety of platforms. You will see pointers to documents, directions for running Medley online, installing Medley, and reporting bugs.

History of Interlisp
Discover the history of Interlisp including research materials and an extensive biography.

**Comment by masinter** [comment]
The thing we're asking people to "try running" is "Medley". The history is mainly the "Interlisp" history, while the project is the "Medley Interlisp" project. Right now you say "Try running Medley Interlisp" .

Bibliography, not Biography.

**Comment by stumbo** [comment]
Here are the three panels with Kathryn and Larry's comments addressed:
image

**Comment by stumbo** [comment]
This commit fixes the Table of Contents.  I'll clean up the conflicts and it should be ready to be merged back into lmmwip1.  From there we can deploy to main if we're happy with the overall structure of the site.

**Pull request merged**
