### PR TITLE
Removed Twitter, added Mastodon and Bluesky.

### PR DESCRIPTION
**Pull request by hjellinek**
Issue #1887: Removed Twitter link from footer, add Mastodon and Bluesky.

### CODE REVIEW

**Review by stumbo — APPROVED** [review]
Looks good to me.

**Comment by hjellinek** [comment]
I found an error that I still need to address.

**Comment by hjellinek** [comment]
OK, @stumbo, can you please redeploy it?

**Comment by stumbo** [comment]
| Can you please redeploy it?

@hjellinek  Done, it's live at:

https://stumbo.github.io/InterlispDraft.github.io/

**Comment by hjellinek** [comment]
Thanks, @stumbo.

**Pull request merged**
