### PR TITLE
Use the DOI field to build missing URL for bibliography.json file.

### PR DESCRIPTION
**Pull request by MattHeffron**
When URL field is missing in Zotero json data, use the DOI field to build a URL for the `bibliography.json` file.
Add debugging/collections/tags/types files generation under conditionals in `scripts/update_bibliography.sh`.
This includes the PR #210 changes.
See also the discussion in [Issue #1534](https://github.com/Interlisp/medley/issues/1534)

### CODE REVIEW

**Comment by stumbo** [comment]
Matt - I ran your updated script and the output, `bibliography.json` no longer works with our site.  I assume there are some changes that need to be reflected in `layouts/shortcodes/bibTable.html`.  I haven't had a chance to look any deeper into the issue.

**Comment by MattHeffron** [comment]
> Matt - I ran your updated script and the output, `bibliography.json` no longer works with our site. I assume there are some changes that need to be reflected in `layouts/shortcodes/bibTable.html`. I haven't had a chance to look any deeper into the issue.

This works on my system, so what should I update locally (Hugo?) to try to reproduce this failure?
(I will be off-line until about October 11.)

**Comment by stumbo** [comment]
I'll dig deeper over the next few days.  We can sync up when you're back online.

**Comment by stumbo** [comment]
I spent a little time and ended up merging this into my staging branch - it appears to have deployed correctly.  You can go to [https://stumbo.github.io/InterlispDraft.github.io/history/bibliography/](https://stumbo.github.io/InterlispDraft.github.io/history/bibliography/) to see the bibliography built with this PR (#242)  and my updates for robots.txt.  PR (#239)

**Review by stumbo — APPROVED** [review]
Based on successfully deploying to staging site.  The 1991 classic, **PEPYS: Generating Autobiographies by Automatic Tracking** appears to be a case where a url was missing and the doi was used to build a working url.  It works correctly in the newly build bibliography.

**Pull request merged**
